services:
  qwen3-asr:
    image: quantatrisk/qwen3-asr:cpu-latest
    container_name: qwen3-asr-cpu
    ports:
      - "${NGINX_PORT:-17003}:8000"
    volumes:
      - ./temp:/app/temp
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models/modelscope:/root/.cache/modelscope
      - ./models/huggingface:/root/.cache/huggingface
    environment:
      API_KEY: ${API_KEY:-}
      HF_HUB_OFFLINE: ${HF_HUB_OFFLINE:-0}
      HF_ENDPOINT: ${HF_ENDPOINT:-}
      QWEN3_ASR_MODEL: ${QWEN3_ASR_MODEL:-}
    restart: unless-stopped
