services:
  qwen3-asr:
    image: quantatrisk/qwen3-asr:gpu-latest
    container_name: qwen3-asr
    ports:
      - "${NGINX_PORT:-9101}:8000"
    volumes:
      - ./app:/app/app
      - ./scripts:/app/scripts
      - ./temp:/app/temp
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models/modelscope:/root/.cache/modelscope
      - ./models/huggingface:/root/.cache/huggingface
    runtime: nvidia
    environment:
      API_KEY: ${API_KEY:-}
      HF_HUB_OFFLINE: ${HF_HUB_OFFLINE:-0}
      HF_ENDPOINT: ${HF_ENDPOINT:-}
      QWEN3_ASR_MODEL: ${QWEN3_ASR_MODEL:-}
      CUDA_VISIBLE_DEVICES: ${CUDA_VISIBLE_DEVICES:-0}
      QWEN_GPU_MEMORY_UTILIZATION: ${QWEN_GPU_MEMORY_UTILIZATION:-}
      QWEN_FORCE_ALIGNER_GPU_MEMORY_UTILIZATION: ${QWEN_FORCE_ALIGNER_GPU_MEMORY_UTILIZATION:-}
      QWEN_IDLE_UNLOAD_TIMEOUT: ${QWEN_IDLE_UNLOAD_TIMEOUT:-300}
    restart: unless-stopped
